# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Git/SimpleCPU/Constraints/Cache02.xdc

# Block Designs: D:/Git/SimpleCPU/Module/Cache/BlockDesign/Cache02Data/Cache02Data.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cache02Data || ORIG_REF_NAME==Cache02Data} -quiet] -quiet

# IP: D:/Git/SimpleCPU/Module/Cache/BlockDesign/Cache02Data/ip/Cache02Data_blk_mem_gen_0_0/Cache02Data_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cache02Data_blk_mem_gen_0_0 || ORIG_REF_NAME==Cache02Data_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: D:/Git/SimpleCPU/Module/Storage/BlockDesign/MemCacheData/MemCacheData.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MemCacheData || ORIG_REF_NAME==MemCacheData} -quiet] -quiet

# IP: d:/Git/SimpleCPU/Module/Storage/BlockDesign/MemCacheData/ip/MemCacheData_dist_mem_gen_0_1/MemCacheData_dist_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MemCacheData_dist_mem_gen_0_1 || ORIG_REF_NAME==MemCacheData_dist_mem_gen_0_1} -quiet] -quiet

# XDC: D:/Git/SimpleCPU/Module/Cache/BlockDesign/Cache02Data/Cache02Data_ooc.xdc

# XDC: D:/Git/SimpleCPU/Module/Storage/BlockDesign/MemCacheData/MemCacheData_ooc.xdc
