# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Git/SimpleCPU01/SimpleCPU01Project/SimpleCPU01Project.srcs/sources_1/bd/SimpleCPU01Design/ip/SimpleCPU01Design_dist_mem_gen_0_0/SimpleCPU01Design_dist_mem_gen_0_0.xci
# IP: The module: 'SimpleCPU01Design_dist_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Git/SimpleCPU01/SimpleCPU01Project/SimpleCPU01Project.gen/sources_1/bd/SimpleCPU01Design/ip/SimpleCPU01Design_dist_mem_gen_0_0/SimpleCPU01Design_dist_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SimpleCPU01Design_dist_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Git/SimpleCPU01/SimpleCPU01Project/SimpleCPU01Project.srcs/sources_1/bd/SimpleCPU01Design/ip/SimpleCPU01Design_dist_mem_gen_0_0/SimpleCPU01Design_dist_mem_gen_0_0.xci
# IP: The module: 'SimpleCPU01Design_dist_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Git/SimpleCPU01/SimpleCPU01Project/SimpleCPU01Project.gen/sources_1/bd/SimpleCPU01Design/ip/SimpleCPU01Design_dist_mem_gen_0_0/SimpleCPU01Design_dist_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SimpleCPU01Design_dist_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
