# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Git/SimpleCPU/Module/Cache/BlockDesign/DataMemCacheFourSetAssociative/ip/DataMemCacheFourSetAssociative_blk_mem_gen_0_0/DataMemCacheFourSetAssociative_blk_mem_gen_0_0.xci
# IP: The module: 'DataMemCacheFourSetAssociative_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Git/SimpleCPU/Module/Cache/BlockDesign/DataMemCacheFourSetAssociative/ip/DataMemCacheFourSetAssociative_blk_mem_gen_0_0/DataMemCacheFourSetAssociative_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataMemCacheFourSetAssociative_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Git/SimpleCPU/Module/Cache/BlockDesign/DataMemCacheFourSetAssociative/ip/DataMemCacheFourSetAssociative_blk_mem_gen_0_0/DataMemCacheFourSetAssociative_blk_mem_gen_0_0.xci
# IP: The module: 'DataMemCacheFourSetAssociative_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Git/SimpleCPU/Module/Cache/BlockDesign/DataMemCacheFourSetAssociative/ip/DataMemCacheFourSetAssociative_blk_mem_gen_0_0/DataMemCacheFourSetAssociative_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataMemCacheFourSetAssociative_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
