# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Git/SimpleCPU/Constraints/Cache01.xdc

# Block Designs: D:/Git/SimpleCPU/Module/Storage/BlockDesign/MemCacheData/MemCacheData.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MemCacheData || ORIG_REF_NAME==MemCacheData} -quiet] -quiet

# IP: D:/Git/SimpleCPU/Module/Storage/BlockDesign/MemCacheData/ip/MemCacheData_dist_mem_gen_0_1/MemCacheData_dist_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MemCacheData_dist_mem_gen_0_1 || ORIG_REF_NAME==MemCacheData_dist_mem_gen_0_1} -quiet] -quiet

# Block Designs: D:/Git/SimpleCPU/Module/Cache/BlockDesign/DataMemCacheFourSetAssociative/DataMemCacheFourSetAssociative.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DataMemCacheFourSetAssociative || ORIG_REF_NAME==DataMemCacheFourSetAssociative} -quiet] -quiet

# IP: d:/Git/SimpleCPU/Module/Cache/BlockDesign/DataMemCacheFourSetAssociative/ip/DataMemCacheFourSetAssociative_blk_mem_gen_0_0/DataMemCacheFourSetAssociative_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DataMemCacheFourSetAssociative_blk_mem_gen_0_0 || ORIG_REF_NAME==DataMemCacheFourSetAssociative_blk_mem_gen_0_0} -quiet] -quiet

# XDC: D:/Git/SimpleCPU/Module/Storage/BlockDesign/MemCacheData/MemCacheData_ooc.xdc

# XDC: D:/Git/SimpleCPU/Module/Cache/BlockDesign/DataMemCacheFourSetAssociative/DataMemCacheFourSetAssociative_ooc.xdc
