# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Git/SimpleCPU01/Constraints/Chip_InstrIP.xdc

# Block Designs: bd/SimpleCPU01Design/SimpleCPU01Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SimpleCPU01Design || ORIG_REF_NAME==SimpleCPU01Design} -quiet] -quiet

# IP: bd/SimpleCPU01Design/ip/SimpleCPU01Design_dist_mem_gen_0_0/SimpleCPU01Design_dist_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SimpleCPU01Design_dist_mem_gen_0_0 || ORIG_REF_NAME==SimpleCPU01Design_dist_mem_gen_0_0} -quiet] -quiet

# XDC: d:/Git/SimpleCPU01/SimpleCPU01Project/SimpleCPU01Project.gen/sources_1/bd/SimpleCPU01Design/SimpleCPU01Design_ooc.xdc
