# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Git/SimpleCPU/Module/Storage/BlockDesign/MemCacheData/ip/MemCacheData_dist_mem_gen_0_1/MemCacheData_dist_mem_gen_0_1.xci
# IP: The module: 'MemCacheData_dist_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Git/SimpleCPU/Module/Storage/BlockDesign/MemCacheData/ip/MemCacheData_dist_mem_gen_0_1/MemCacheData_dist_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MemCacheData_dist_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Git/SimpleCPU/Module/Storage/BlockDesign/MemCacheData/ip/MemCacheData_dist_mem_gen_0_1/MemCacheData_dist_mem_gen_0_1.xci
# IP: The module: 'MemCacheData_dist_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Git/SimpleCPU/Module/Storage/BlockDesign/MemCacheData/ip/MemCacheData_dist_mem_gen_0_1/MemCacheData_dist_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MemCacheData_dist_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
